# NOTE: This dockerfile was leveraged HEAVILY from: https://www.docker.com/blog/how-to-dockerize-react-app/
ARG NODE_VERSION=24.19.0-alpine

FROM node:${NODE_VERSION} AS builder

#define a working directory
WORKDIR /app

# copy node.js' dependencies and build them
COPY package*.json ./

RUN npm install ci

COPY . . 

RUN npm run build


EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]
