// Inline CSS Styles Object
export const styles = {
    container: {
        maxWidth: '700px',
        margin: '40px auto',
        padding: '24px',
        fontFamily: 'Arial, sans-serif',
        backgroundColor: '#f8f9fa',
        borderRadius: '8px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    },
    heading: {
        color: '#2c3e50',
        borderBottom: '2px solid #e2e8f0',
        paddingBottom: '12px',
        marginTop: 0,
    },
    subHeading: {
        fontSize: '18px',
        color: '#34495e',
        marginTop: 0,
    },
    card: {
        backgroundColor: '#ffffff',
        padding: '16px',
        borderRadius: '6px',
        border: '1px solid #e2e8f0',
        marginTop: '16px',
    },
    codeBlock: {
        backgroundColor: '#1e293b',
        color: '#38bdf8',
        padding: '12px',
        borderRadius: '4px',
        overflowX: 'auto',
        fontSize: '14px',
        margin: 0,
    },
    loginButton: {
        display: 'inline-block',
        padding: '10px 16px',
        backgroundColor: '#24292e',
        color: '#fff',
        textDecoration: 'none',
        borderRadius: '4px',
        fontWeight: 'bold',
    },
    logoutButton: {
        display: 'inline-block',
        marginTop: '10px',
        padding: '6px 12px',
        backgroundColor: '#e53e3e',
        color: '#fff',
        textDecoration: 'none',
        borderRadius: '4px',
    },

    //OSRS elements
    label: {
        display: 'block',
        marginBottom: '4px',
        fontSize: '14px',
        fontWeight: 'bold',
        color: '#475569',
    },
    input: {
        width: '100%',
        padding: '8px',
        borderRadius: '4px',
        border: '1px solid #cbd5e1',
        boxSizing: 'border-box',
    },
    button: {
        padding: '10px 16px',
        backgroundColor: '#2563eb',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
    dangerButton: {
        padding: '10px 16px',
        backgroundColor: '#dc2626',
        color: '#fff',
        border: 'none',
        borderRadius: '4px',
        fontWeight: 'bold',
        cursor: 'pointer',
    },
};